default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # Otros par치metros...

development:
  <<: *default
  database: db/development.sqlite3
  # Otros par치metros...

# Otros entornos...

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # Otros par치metros...

development:
  <<: *default
  database: db/development.sqlite3
  # Otros par치metros...

# Otros entornos...

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
